#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p /config/{mylar,scripts}

# copy scripts folder to config
if [[ ! -f /config/scripts/autoProcessComics.py ]]; then
    cp -pr /app/mylar3/post-processing/* /config/scripts/
fi

# permissions
lsiown -R abc:abc \
    /config
